# Generated by Django 4.1.5 on 2023-07-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fetch_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='external_id',
            field=models.CharField(max_length=10),
        ),
    ]
