# Generated by Django 4.1.5 on 2023-08-07 07:04

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fetch_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.CharField(default=api.utils.hex_generator, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tracks', models.ManyToManyField(related_name='playlists', to='api.track')),
            ],
        ),
    ]
