# Generated by Django 4.1.5 on 2023-09-17 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_playlist_playlisttrack_playlist_tracks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlisttrack',
            options={'get_latest_by': 'order'},
        ),
    ]
