# Generated by Django 4.1.5 on 2023-12-04 14:48
from django.db import migrations


def add_test_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.create_user(username='test', password='test', is_superuser=True, email='test@test.com', is_active=True)


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_playlist_playlisttrack_playlist_tracks_playlist_user'),
    ]

    operations = [
        migrations.RunPython(add_test_user),
    ]
