# Generated by Django 4.1.5 on 2023-07-27 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_playlist_id'),
    ]

    operations = [
    ]
