# Generated by Django 4.1.5 on 2023-09-17 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_playlisttrack_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlisttrack',
            unique_together={('playlist_id', 'track_id'), ('playlist_id', 'order')},
        ),
    ]
