# Generated by Django 4.1.5 on 2023-07-27 21:01

import api.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230727_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlist',
            name='id',
            field=models.CharField(default=api.models.generate_custom_id, max_length=10, primary_key=True, serialize=False),
        ),
    ]
